server:
  port: 8087
security:
  oauth2:
    client:
      client-id: web2
      client-secret: 123456
      #登录认证接口路径
      user-authorization-uri: http://www.sso.com:8080/oauth/authorize
      #访问token的路径
      access-token-uri: http://www.sso.com:8080/oauth/token
      registered-redirect-uri:
    resource:
      jwt:
        #获取token的路径
        key-uri: http://www.sso.com:8080/oauth/token_key
